var express = require('express');
var router = express.Router();

router.get('/about', function(req, res){
    // Test first
    // res.send("This text is generated by expressjs");

    res.render('about', {
        pageTitle : 'About',
        pageId : 'about'
    });
});

module.exports = router;